# ==============================================
# Configuracoes - Ambiente Staging
# ==============================================
server.port=8080

# Logging detalhado para staging
logging.level.com.fiap.gestao.residuos=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
