-- =====================================================
-- Sistema de Gestão de Resíduos e Reciclagem
-- Script de Inserção de Dados
-- Oracle SQL
-- =====================================================

-- Habilitar saída de mensagens
SET SERVEROUTPUT ON;

-- =====================================================
-- Inserção: TIPO_RESIDUO (6 registros)
-- =====================================================
INSERT INTO TIPO_RESIDUO (ID_TIPO_RESIDUO, NOME, DESCRICAO, COR_IDENTIFICACAO, IMPACTO_AMBIENTAL, DATA_CADASTRO)
VALUES (SEQ_TIPO_RESIDUO.NEXTVAL, 'Plástico', 'Garrafas PET, embalagens plásticas, sacolas', 'Vermelho', 'ALTO', SYSDATE);

INSERT INTO TIPO_RESIDUO (ID_TIPO_RESIDUO, NOME, DESCRICAO, COR_IDENTIFICACAO, IMPACTO_AMBIENTAL, DATA_CADASTRO)
VALUES (SEQ_TIPO_RESIDUO.NEXTVAL, 'Papel', 'Papel, papelão, jornais, revistas', 'Azul', 'MEDIO', SYSDATE);

INSERT INTO TIPO_RESIDUO (ID_TIPO_RESIDUO, NOME, DESCRICAO, COR_IDENTIFICACAO, IMPACTO_AMBIENTAL, DATA_CADASTRO)
VALUES (SEQ_TIPO_RESIDUO.NEXTVAL, 'Vidro', 'Garrafas, potes, frascos de vidro', 'Verde', 'BAIXO', SYSDATE);

INSERT INTO TIPO_RESIDUO (ID_TIPO_RESIDUO, NOME, DESCRICAO, COR_IDENTIFICACAO, IMPACTO_AMBIENTAL, DATA_CADASTRO)
VALUES (SEQ_TIPO_RESIDUO.NEXTVAL, 'Metal', 'Latas de alumínio, ferragens, metais diversos', 'Amarelo', 'MEDIO', SYSDATE);

INSERT INTO TIPO_RESIDUO (ID_TIPO_RESIDUO, NOME, DESCRICAO, COR_IDENTIFICACAO, IMPACTO_AMBIENTAL, DATA_CADASTRO)
VALUES (SEQ_TIPO_RESIDUO.NEXTVAL, 'Orgânico', 'Restos de alimentos, cascas, resíduos biodegradáveis', 'Marrom', 'BAIXO', SYSDATE);

INSERT INTO TIPO_RESIDUO (ID_TIPO_RESIDUO, NOME, DESCRICAO, COR_IDENTIFICACAO, IMPACTO_AMBIENTAL, DATA_CADASTRO)
VALUES (SEQ_TIPO_RESIDUO.NEXTVAL, 'Eletrônico', 'Eletrônicos, pilhas, baterias, componentes', 'Laranja', 'ALTO', SYSDATE);

COMMIT;

-- =====================================================
-- Inserção: CONTAINER (8 registros)
-- =====================================================
INSERT INTO CONTAINER (ID_CONTAINER, ID_TIPO_RESIDUO, LOCALIZACAO, CAPACIDADE_MAXIMA, CAPACIDADE_ATUAL, PERCENTUAL_OCUPACAO, STATUS, DATA_INSTALACAO, ULTIMA_COLETA)
VALUES (SEQ_CONTAINER.NEXTVAL, 1, 'Praça Central - Zona Norte', 100.00, 45.50, 45.50, 'ATIVO', TO_DATE('2024-01-15', 'YYYY-MM-DD'), TO_DATE('2025-10-01', 'YYYY-MM-DD'));

INSERT INTO CONTAINER (ID_CONTAINER, ID_TIPO_RESIDUO, LOCALIZACAO, CAPACIDADE_MAXIMA, CAPACIDADE_ATUAL, PERCENTUAL_OCUPACAO, STATUS, DATA_INSTALACAO, ULTIMA_COLETA)
VALUES (SEQ_CONTAINER.NEXTVAL, 2, 'Parque Ecológico - Centro', 120.00, 85.00, 70.83, 'ATIVO', TO_DATE('2024-01-20', 'YYYY-MM-DD'), TO_DATE('2025-09-30', 'YYYY-MM-DD'));

INSERT INTO CONTAINER (ID_CONTAINER, ID_TIPO_RESIDUO, LOCALIZACAO, CAPACIDADE_MAXIMA, CAPACIDADE_ATUAL, PERCENTUAL_OCUPACAO, STATUS, DATA_INSTALACAO, ULTIMA_COLETA)
VALUES (SEQ_CONTAINER.NEXTVAL, 3, 'Shopping Popular - Zona Sul', 80.00, 72.00, 90.00, 'ATIVO', TO_DATE('2024-02-01', 'YYYY-MM-DD'), TO_DATE('2025-09-28', 'YYYY-MM-DD'));

INSERT INTO CONTAINER (ID_CONTAINER, ID_TIPO_RESIDUO, LOCALIZACAO, CAPACIDADE_MAXIMA, CAPACIDADE_ATUAL, PERCENTUAL_OCUPACAO, STATUS, DATA_INSTALACAO, ULTIMA_COLETA)
VALUES (SEQ_CONTAINER.NEXTVAL, 4, 'Terminal Rodoviário - Centro', 90.00, 25.00, 27.78, 'ATIVO', TO_DATE('2024-02-10', 'YYYY-MM-DD'), TO_DATE('2025-10-02', 'YYYY-MM-DD'));

INSERT INTO CONTAINER (ID_CONTAINER, ID_TIPO_RESIDUO, LOCALIZACAO, CAPACIDADE_MAXIMA, CAPACIDADE_ATUAL, PERCENTUAL_OCUPACAO, STATUS, DATA_INSTALACAO, ULTIMA_COLETA)
VALUES (SEQ_CONTAINER.NEXTVAL, 5, 'Mercado Municipal - Zona Leste', 150.00, 140.00, 93.33, 'ATIVO', TO_DATE('2024-02-15', 'YYYY-MM-DD'), TO_DATE('2025-09-25', 'YYYY-MM-DD'));

INSERT INTO CONTAINER (ID_CONTAINER, ID_TIPO_RESIDUO, LOCALIZACAO, CAPACIDADE_MAXIMA, CAPACIDADE_ATUAL, PERCENTUAL_OCUPACAO, STATUS, DATA_INSTALACAO, ULTIMA_COLETA)
VALUES (SEQ_CONTAINER.NEXTVAL, 6, 'Universidade Estadual - Campus A', 60.00, 15.00, 25.00, 'ATIVO', TO_DATE('2024-03-01', 'YYYY-MM-DD'), TO_DATE('2025-10-05', 'YYYY-MM-DD'));

INSERT INTO CONTAINER (ID_CONTAINER, ID_TIPO_RESIDUO, LOCALIZACAO, CAPACIDADE_MAXIMA, CAPACIDADE_ATUAL, PERCENTUAL_OCUPACAO, STATUS, DATA_INSTALACAO)
VALUES (SEQ_CONTAINER.NEXTVAL, 1, 'Parque Industrial - Zona Oeste', 100.00, 100.00, 100.00, 'CHEIO', TO_DATE('2024-03-10', 'YYYY-MM-DD'));

INSERT INTO CONTAINER (ID_CONTAINER, ID_TIPO_RESIDUO, LOCALIZACAO, CAPACIDADE_MAXIMA, CAPACIDADE_ATUAL, PERCENTUAL_OCUPACAO, STATUS, DATA_INSTALACAO)
VALUES (SEQ_CONTAINER.NEXTVAL, 2, 'Hospital Central - Emergência', 110.00, 0.00, 0.00, 'MANUTENCAO', TO_DATE('2024-03-15', 'YYYY-MM-DD'));

COMMIT;

-- =====================================================
-- Inserção: RESIDUO_DESCARTADO (10 registros)
-- =====================================================
INSERT INTO RESIDUO_DESCARTADO (ID_DESCARTE, ID_CONTAINER, ID_TIPO_RESIDUO, PESO_KG, DATA_DESCARTE, DESCARTE_CORRETO, OBSERVACAO)
VALUES (SEQ_RESIDUO_DESCARTADO.NEXTVAL, 1, 1, 5.5, TO_DATE('2025-10-05 08:30', 'YYYY-MM-DD HH24:MI'), 'S', 'Garrafas PET vazias');

INSERT INTO RESIDUO_DESCARTADO (ID_DESCARTE, ID_CONTAINER, ID_TIPO_RESIDUO, PESO_KG, DATA_DESCARTE, DESCARTE_CORRETO, OBSERVACAO)
VALUES (SEQ_RESIDUO_DESCARTADO.NEXTVAL, 1, 1, 3.2, TO_DATE('2025-10-05 14:15', 'YYYY-MM-DD HH24:MI'), 'S', 'Embalagens plásticas');

INSERT INTO RESIDUO_DESCARTADO (ID_DESCARTE, ID_CONTAINER, ID_TIPO_RESIDUO, PESO_KG, DATA_DESCARTE, DESCARTE_CORRETO, OBSERVACAO)
VALUES (SEQ_RESIDUO_DESCARTADO.NEXTVAL, 2, 2, 8.0, TO_DATE('2025-10-06 09:00', 'YYYY-MM-DD HH24:MI'), 'S', 'Caixas de papelão');

INSERT INTO RESIDUO_DESCARTADO (ID_DESCARTE, ID_CONTAINER, ID_TIPO_RESIDUO, PESO_KG, DATA_DESCARTE, DESCARTE_CORRETO, OBSERVACAO)
VALUES (SEQ_RESIDUO_DESCARTADO.NEXTVAL, 2, 1, 2.5, TO_DATE('2025-10-06 11:30', 'YYYY-MM-DD HH24:MI'), 'N', 'Plástico descartado incorretamente no container de papel');

INSERT INTO RESIDUO_DESCARTADO (ID_DESCARTE, ID_CONTAINER, ID_TIPO_RESIDUO, PESO_KG, DATA_DESCARTE, DESCARTE_CORRETO, OBSERVACAO)
VALUES (SEQ_RESIDUO_DESCARTADO.NEXTVAL, 3, 3, 12.0, TO_DATE('2025-10-06 15:45', 'YYYY-MM-DD HH24:MI'), 'S', 'Garrafas de vidro');

INSERT INTO RESIDUO_DESCARTADO (ID_DESCARTE, ID_CONTAINER, ID_TIPO_RESIDUO, PESO_KG, DATA_DESCARTE, DESCARTE_CORRETO, OBSERVACAO)
VALUES (SEQ_RESIDUO_DESCARTADO.NEXTVAL, 4, 4, 4.5, TO_DATE('2025-10-07 08:00', 'YYYY-MM-DD HH24:MI'), 'S', 'Latas de alumínio');

INSERT INTO RESIDUO_DESCARTADO (ID_DESCARTE, ID_CONTAINER, ID_TIPO_RESIDUO, PESO_KG, DATA_DESCARTE, DESCARTE_CORRETO, OBSERVACAO)
VALUES (SEQ_RESIDUO_DESCARTADO.NEXTVAL, 5, 5, 18.5, TO_DATE('2025-10-07 10:30', 'YYYY-MM-DD HH24:MI'), 'S', 'Restos de frutas e verduras');

INSERT INTO RESIDUO_DESCARTADO (ID_DESCARTE, ID_CONTAINER, ID_TIPO_RESIDUO, PESO_KG, DATA_DESCARTE, DESCARTE_CORRETO, OBSERVACAO)
VALUES (SEQ_RESIDUO_DESCARTADO.NEXTVAL, 5, 5, 22.0, TO_DATE('2025-10-07 12:00', 'YYYY-MM-DD HH24:MI'), 'S', 'Resíduos orgânicos do restaurante');

INSERT INTO RESIDUO_DESCARTADO (ID_DESCARTE, ID_CONTAINER, ID_TIPO_RESIDUO, PESO_KG, DATA_DESCARTE, DESCARTE_CORRETO, OBSERVACAO)
VALUES (SEQ_RESIDUO_DESCARTADO.NEXTVAL, 6, 6, 3.0, TO_DATE('2025-10-07 14:20', 'YYYY-MM-DD HH24:MI'), 'S', 'Pilhas e baterias');

INSERT INTO RESIDUO_DESCARTADO (ID_DESCARTE, ID_CONTAINER, ID_TIPO_RESIDUO, PESO_KG, DATA_DESCARTE, DESCARTE_CORRETO, OBSERVACAO)
VALUES (SEQ_RESIDUO_DESCARTADO.NEXTVAL, 3, 5, 5.0, TO_DATE('2025-10-07 16:00', 'YYYY-MM-DD HH24:MI'), 'N', 'Resíduo orgânico descartado incorretamente no container de vidro');

COMMIT;

-- =====================================================
-- Inserção: COLETA (7 registros)
-- =====================================================
INSERT INTO COLETA (ID_COLETA, ID_CONTAINER, DATA_COLETA, PESO_COLETADO, EMPRESA_RESPONSAVEL, STATUS_COLETA, DESTINO_FINAL, DATA_AGENDAMENTO, OBSERVACAO)
VALUES (SEQ_COLETA.NEXTVAL, 1, TO_DATE('2025-10-01', 'YYYY-MM-DD'), 95.00, 'EcoColeta Ltda', 'REALIZADA', 'Centro de Reciclagem Plásticos SP', TO_DATE('2025-09-28', 'YYYY-MM-DD'), 'Coleta realizada conforme programado');

INSERT INTO COLETA (ID_COLETA, ID_CONTAINER, DATA_COLETA, PESO_COLETADO, EMPRESA_RESPONSAVEL, STATUS_COLETA, DESTINO_FINAL, DATA_AGENDAMENTO, OBSERVACAO)
VALUES (SEQ_COLETA.NEXTVAL, 2, TO_DATE('2025-09-30', 'YYYY-MM-DD'), 110.00, 'Recicla Mais', 'REALIZADA', 'Fábrica de Papel Reciclado', TO_DATE('2025-09-27', 'YYYY-MM-DD'), 'Material em bom estado');

INSERT INTO COLETA (ID_COLETA, ID_CONTAINER, DATA_COLETA, PESO_COLETADO, EMPRESA_RESPONSAVEL, STATUS_COLETA, DESTINO_FINAL, DATA_AGENDAMENTO, OBSERVACAO)
VALUES (SEQ_COLETA.NEXTVAL, 3, TO_DATE('2025-09-28', 'YYYY-MM-DD'), 75.00, 'VidroLimpo', 'REALIZADA', 'Indústria de Vidros Recicláveis', TO_DATE('2025-09-25', 'YYYY-MM-DD'), 'Vidro sem contaminação');

INSERT INTO COLETA (ID_COLETA, ID_CONTAINER, DATA_COLETA, PESO_COLETADO, EMPRESA_RESPONSAVEL, STATUS_COLETA, DESTINO_FINAL, DATA_AGENDAMENTO, OBSERVACAO)
VALUES (SEQ_COLETA.NEXTVAL, 4, TO_DATE('2025-10-02', 'YYYY-MM-DD'), 85.00, 'MetalRecicla', 'REALIZADA', 'Fundição de Alumínio', TO_DATE('2025-09-29', 'YYYY-MM-DD'), 'Alta qualidade do metal');

INSERT INTO COLETA (ID_COLETA, ID_CONTAINER, DATA_COLETA, PESO_COLETADO, EMPRESA_RESPONSAVEL, STATUS_COLETA, DESTINO_FINAL, DATA_AGENDAMENTO, OBSERVACAO)
VALUES (SEQ_COLETA.NEXTVAL, 5, TO_DATE('2025-09-25', 'YYYY-MM-DD'), 145.00, 'CompostBrasil', 'REALIZADA', 'Usina de Compostagem', TO_DATE('2025-09-22', 'YYYY-MM-DD'), 'Material orgânico para compostagem');

INSERT INTO COLETA (ID_COLETA, ID_CONTAINER, DATA_COLETA, PESO_COLETADO, EMPRESA_RESPONSAVEL, STATUS_COLETA, DESTINO_FINAL, DATA_AGENDAMENTO)
VALUES (SEQ_COLETA.NEXTVAL, 7, NULL, NULL, 'EcoColeta Ltda', 'AGENDADA', 'Centro de Reciclagem Plásticos SP', TO_DATE('2025-10-08', 'YYYY-MM-DD'));

INSERT INTO COLETA (ID_COLETA, ID_CONTAINER, DATA_COLETA, PESO_COLETADO, EMPRESA_RESPONSAVEL, STATUS_COLETA, DESTINO_FINAL, DATA_AGENDAMENTO, OBSERVACAO)
VALUES (SEQ_COLETA.NEXTVAL, 8, NULL, NULL, 'Recicla Mais', 'CANCELADA', NULL, TO_DATE('2025-10-03', 'YYYY-MM-DD'), 'Container em manutenção');

COMMIT;

-- =====================================================
-- Inserção: NOTIFICACAO (8 registros)
-- =====================================================
INSERT INTO NOTIFICACAO (ID_NOTIFICACAO, ID_CONTAINER, TIPO_NOTIFICACAO, MENSAGEM, DATA_GERACAO, PRIORIDADE, STATUS)
VALUES (SEQ_NOTIFICACAO.NEXTVAL, 3, 'ALERTA_CAPACIDADE', 'Container de Vidro no Shopping Popular atingiu 90% da capacidade. Agendar coleta urgente.', TO_DATE('2025-10-06', 'YYYY-MM-DD'), 'ALTA', 'PENDENTE');

INSERT INTO NOTIFICACAO (ID_NOTIFICACAO, ID_CONTAINER, TIPO_NOTIFICACAO, MENSAGEM, DATA_GERACAO, PRIORIDADE, STATUS)
VALUES (SEQ_NOTIFICACAO.NEXTVAL, 5, 'ALERTA_CAPACIDADE', 'Container Orgânico no Mercado Municipal atingiu 93% da capacidade. Coleta necessária.', TO_DATE('2025-10-07', 'YYYY-MM-DD'), 'ALTA', 'PENDENTE');

INSERT INTO NOTIFICACAO (ID_NOTIFICACAO, ID_CONTAINER, TIPO_NOTIFICACAO, MENSAGEM, DATA_GERACAO, PRIORIDADE, STATUS)
VALUES (SEQ_NOTIFICACAO.NEXTVAL, 7, 'CONTAINER_CHEIO', 'Container de Plástico no Parque Industrial está 100% cheio. Coleta imediata necessária!', TO_DATE('2025-10-07', 'YYYY-MM-DD'), 'ALTA', 'PENDENTE');

INSERT INTO NOTIFICACAO (ID_NOTIFICACAO, ID_CONTAINER, TIPO_NOTIFICACAO, MENSAGEM, DATA_GERACAO, PRIORIDADE, STATUS, DATA_RESOLUCAO)
VALUES (SEQ_NOTIFICACAO.NEXTVAL, 2, 'DESCARTE_INCORRETO', 'Detectado descarte de Plástico no container de Papel no Parque Ecológico.', TO_DATE('2025-10-06', 'YYYY-MM-DD'), 'MEDIA', 'RESOLVIDA', TO_DATE('2025-10-06', 'YYYY-MM-DD'));

INSERT INTO NOTIFICACAO (ID_NOTIFICACAO, ID_CONTAINER, TIPO_NOTIFICACAO, MENSAGEM, DATA_GERACAO, PRIORIDADE, STATUS, DATA_RESOLUCAO)
VALUES (SEQ_NOTIFICACAO.NEXTVAL, 3, 'DESCARTE_INCORRETO', 'Detectado descarte de Resíduo Orgânico no container de Vidro no Shopping Popular.', TO_DATE('2025-10-07', 'YYYY-MM-DD'), 'MEDIA', 'VISUALIZADA', NULL);

INSERT INTO NOTIFICACAO (ID_NOTIFICACAO, ID_CONTAINER, TIPO_NOTIFICACAO, MENSAGEM, DATA_GERACAO, PRIORIDADE, STATUS, DATA_RESOLUCAO)
VALUES (SEQ_NOTIFICACAO.NEXTVAL, 1, 'COLETA_REALIZADA', 'Coleta realizada com sucesso. Container resetado.', TO_DATE('2025-10-01', 'YYYY-MM-DD'), 'BAIXA', 'RESOLVIDA', TO_DATE('2025-10-01', 'YYYY-MM-DD'));

INSERT INTO NOTIFICACAO (ID_NOTIFICACAO, ID_CONTAINER, TIPO_NOTIFICACAO, MENSAGEM, DATA_GERACAO, PRIORIDADE, STATUS)
VALUES (SEQ_NOTIFICACAO.NEXTVAL, 8, 'MANUTENCAO', 'Container em manutenção. Coleta cancelada temporariamente.', TO_DATE('2025-10-03', 'YYYY-MM-DD'), 'MEDIA', 'PENDENTE');

INSERT INTO NOTIFICACAO (ID_NOTIFICACAO, ID_CONTAINER, TIPO_NOTIFICACAO, MENSAGEM, DATA_GERACAO, PRIORIDADE, STATUS)
VALUES (SEQ_NOTIFICACAO.NEXTVAL, NULL, 'RELATORIO_MENSAL', 'Relatório mensal de reciclagem gerado. Total coletado: 510 kg. Impacto ambiental positivo.', TO_DATE('2025-10-01', 'YYYY-MM-DD'), 'BAIXA', 'VISUALIZADA');

COMMIT;

-- =====================================================
-- Verificação dos dados inseridos
-- =====================================================
BEGIN
    DBMS_OUTPUT.PUT_LINE('===================================================');
    DBMS_OUTPUT.PUT_LINE('Dados inseridos com sucesso!');
    DBMS_OUTPUT.PUT_LINE('===================================================');
    
    FOR rec IN (SELECT 'TIPO_RESIDUO' AS TABELA, COUNT(*) AS QTD FROM TIPO_RESIDUO
                UNION ALL
                SELECT 'CONTAINER', COUNT(*) FROM CONTAINER
                UNION ALL
                SELECT 'RESIDUO_DESCARTADO', COUNT(*) FROM RESIDUO_DESCARTADO
                UNION ALL
                SELECT 'COLETA', COUNT(*) FROM COLETA
                UNION ALL
                SELECT 'NOTIFICACAO', COUNT(*) FROM NOTIFICACAO)
    LOOP
        DBMS_OUTPUT.PUT_LINE(RPAD(rec.TABELA, 25) || ': ' || rec.QTD || ' registro(s)');
    END LOOP;
    
    DBMS_OUTPUT.PUT_LINE('===================================================');
END;
/
